title: "WordHoard"
logo: "/images/Wordhoardlogo.jpg"
description: Your personal book management solution
#baseurl: ""
url: "https://cherylkc.github.io/catalog-service/"
theme: jekyll-theme-minimal
include: ['pages']
